language: node_js
node_js:
  - "node"
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: master
  on:
    branch: dev
